apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stedi-haein
spec:
  selector:
    matchLabels: 
      app: redis-stedi-haein # must match spec.template.metadata.labels
  serviceName: redis-stedi-haein
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-stedi-haein
    spec:
      containers:
        - name: redis-stedi-haein
          image: redis:7.0.5-alpine
          imagePullPolicy: Always
          args: ["--requirepass", "${REDIS_PASS}", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: redis
          env:
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis-secrets-haein
                key: REDIS_PASS
          volumeMounts:
            - name: redis-haein-volume
              mountPath: /data
  volumeClaimTemplates: 
  - metadata: 
      name: redis-haein-volume
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-stedi-haein
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector: 
    app: redis-stedi-haein